// =======================================================================================
// Warning. Do not edit this file directly.  This file was built with the SPL generator.
// Eduardo Andrade - 2014-04-09 13:12:38 -0300
// =======================================================================================
package br.com.splgenerator.model.cadastro;

public class Adiantamento {

	private java.util.Date _data;
	private Float _valor;
	private String _finalidade;
	private java.util.Date _dataVencimento;
	private java.util.Date _dataContabilizacao;

	public Adiantamento() { 
	
		_data = null;
	
		_valor = null;
	
		_finalidade = null;
	
		_dataVencimento = null;
	
		_dataContabilizacao = null;
	
	}
	
	
		public java.util.Date getData() { return _data; }
		public void setData( java.util.Date value ) { _data = value; }
	
		public Float getValor() { return _valor; }
		public void setValor( Float value ) { _valor = value; }
	
		public String getFinalidade() { return _finalidade; }
		public void setFinalidade( String value ) { _finalidade = value; }
	
		public java.util.Date getDatavencimento() { return _dataVencimento; }
		public void setDatavencimento( java.util.Date value ) { _dataVencimento = value; }
	
		public java.util.Date getDatacontabilizacao() { return _dataContabilizacao; }
		public void setDatacontabilizacao( java.util.Date value ) { _dataContabilizacao = value; }
	

}

