// =======================================================================================
// Warning. Do not edit this file directly.  This file was built with the SPL generator.
// Eduardo Andrade - 2014-04-09 13:12:38 -0300
// =======================================================================================
package br.com.splgenerator.model.cadastro;

public class ComprovanteDespesa {

	private String _numero;
	private java.util.Date _dataEmissao;
	private Float _valor;
	private String _fornecedor;
	private String _itinerario;
	private Float _quilometragem;
	private String _observacao;
	private br.com.splgenerator.model.cadastro.TipoDespesa _tipoDespesa;

	public ComprovanteDespesa() { 
	
		_numero = null;
	
		_dataEmissao = null;
	
		_valor = null;
	
		_fornecedor = null;
	
		_itinerario = null;
	
		_quilometragem = null;
	
		_observacao = null;
	
		_tipoDespesa = new br.com.splgenerator.model.cadastro.TipoDespesa();
	
	}
	
	
		public String getNumero() { return _numero; }
		public void setNumero( String value ) { _numero = value; }
	
		public java.util.Date getDataemissao() { return _dataEmissao; }
		public void setDataemissao( java.util.Date value ) { _dataEmissao = value; }
	
		public Float getValor() { return _valor; }
		public void setValor( Float value ) { _valor = value; }
	
		public String getFornecedor() { return _fornecedor; }
		public void setFornecedor( String value ) { _fornecedor = value; }
	
		public String getItinerario() { return _itinerario; }
		public void setItinerario( String value ) { _itinerario = value; }
	
		public Float getQuilometragem() { return _quilometragem; }
		public void setQuilometragem( Float value ) { _quilometragem = value; }
	
		public String getObservacao() { return _observacao; }
		public void setObservacao( String value ) { _observacao = value; }
	
		public br.com.splgenerator.model.cadastro.TipoDespesa getTipodespesa() { return _tipoDespesa; }
		public void setTipodespesa( br.com.splgenerator.model.cadastro.TipoDespesa value ) { _tipoDespesa = value; }
	

}

