// =======================================================================================
// Warning. Do not edit this file directly.  This file was built with the SPL generator.
// Eduardo Andrade - 2014-04-09 13:12:38 -0300
// =======================================================================================
package br.com.splgenerator.model.cadastro;

public class DadosFuncionario {

	private long _id;
	private long _idFuncionario;
	private Float _maxAuxilioEstudo;
	private int _percentualReembolsoCursos;
	private boolean _fazReembolsoEstudo;
	private br.com.splgenerator.model.cadastro.CursoFuncionario _cursoFuncionario;

	public DadosFuncionario() { 
	
		_id = 0;
	
		_idFuncionario = 0;
	
		_maxAuxilioEstudo = new Float(0);
	
		_percentualReembolsoCursos = 0;
	
		_fazReembolsoEstudo = false;
	
		_cursoFuncionario = new br.com.splgenerator.model.cadastro.CursoFuncionario();
	
	}
	
	
		public long getId() { return _id; }
		public void setId( long value ) { _id = value; }
	
		public long getIdfuncionario() { return _idFuncionario; }
		public void setIdfuncionario( long value ) { _idFuncionario = value; }
	
		public Float getMaxauxilioestudo() { return _maxAuxilioEstudo; }
		public void setMaxauxilioestudo( Float value ) { _maxAuxilioEstudo = value; }
	
		public int getPercentualreembolsocursos() { return _percentualReembolsoCursos; }
		public void setPercentualreembolsocursos( int value ) { _percentualReembolsoCursos = value; }
	
		public boolean getFazreembolsoestudo() { return _fazReembolsoEstudo; }
		public void setFazreembolsoestudo( boolean value ) { _fazReembolsoEstudo = value; }
	
		public br.com.splgenerator.model.cadastro.CursoFuncionario getCursofuncionario() { return _cursoFuncionario; }
		public void setCursofuncionario( br.com.splgenerator.model.cadastro.CursoFuncionario value ) { _cursoFuncionario = value; }
	

}

