// =======================================================================================
// Warning. Do not edit this file directly.  This file was built with the SPL generator.
// Eduardo Andrade - 2014-04-09 13:12:38 -0300
// =======================================================================================
package br.com.splgenerator.model.cadastro;

public class Empresa {

	private long _id;
	private String _razaoSocial;
	private String _nomeFantasia;
	private String _cnpj;
	private String _endereco;

	public Empresa() { 
	
		_id = 0;
	
		_razaoSocial = null;
	
		_nomeFantasia = null;
	
		_cnpj = null;
	
		_endereco = null;
	
	}
	
	
		public long getId() { return _id; }
		public void setId( long value ) { _id = value; }
	
		public String getRazaosocial() { return _razaoSocial; }
		public void setRazaosocial( String value ) { _razaoSocial = value; }
	
		public String getNomefantasia() { return _nomeFantasia; }
		public void setNomefantasia( String value ) { _nomeFantasia = value; }
	
		public String getCnpj() { return _cnpj; }
		public void setCnpj( String value ) { _cnpj = value; }
	
		public String getEndereco() { return _endereco; }
		public void setEndereco( String value ) { _endereco = value; }
	

}

