// =======================================================================================
// Warning. Do not edit this file directly.  This file was built with the SPL generator.
// Eduardo Andrade - 2014-04-09 13:12:38 -0300
// =======================================================================================
package br.com.splgenerator.model.cadastro;

import java.util.Date;

public class Funcionario {

	private long _id;
	private String _nome;
	private int _idade;
	private String _cpf;
	private String _endereco;
	//private br.com.splgenerator.model.cadastro.DadosFuncionario _dadosFuncionario;
	
	private Date _dataNascimento;
	private Date _dataAdmissao;
	private String email;
	private String banco;
	private int agencia;
	private int conta;

	public Funcionario() { 
		
	}
	
	
		public long getId() { return _id; }
		public void setId( long value ) { _id = value; }
	
		public String getNome() { return _nome; }
		public void setNome( String value ) { _nome = value; }
	
		public int getIdade() { return _idade; }
		public void setIdade( int value ) { _idade = value; }
	
		public String getCpf() { return _cpf; }
		public void setCpf( String value ) { _cpf = value; }
	
		public String getEndereco() { return _endereco; }
		public void setEndereco( String value ) { _endereco = value; }

		public Date getDataNascimento() { return _dataNascimento; }
		public void setDataNascimento(Date _dataNascimento) { this._dataNascimento = _dataNascimento; }

		public Date getDataAdmissao() {
			return _dataAdmissao;
		}
		public void setDataAdmissao(Date _dataAdmissao) {
			this._dataAdmissao = _dataAdmissao;
		}

		public String getEmail() {
			return email;
		}
		public void setEmail(String email) {
			this.email = email;
		}

		public String getBanco() {
			return banco;
		}
		public void setBanco(String banco) {
			this.banco = banco;
		}

		public int getAgencia() {
			return agencia;
		}
		public void setAgencia(int agencia) {
			this.agencia = agencia;
		}

		public int getConta() {
			return conta;
		}
		public void setConta(int conta) {
			this.conta = conta;
		}

}

