// =======================================================================================
// Warning. Do not edit this file directly.  This file was built with the SPL generator.
// Eduardo Andrade - 2014-04-09 13:12:38 -0300
// =======================================================================================
package br.com.splgenerator.model.cadastro;

public class TipoDespesa {

	private long _id;
	private String _descricao;

	public TipoDespesa() { 
	
		_id = 0;
	
		_descricao = null;
	
	}
	
	
		public long getId() { return _id; }
		public void setId( long value ) { _id = value; }
	
		public String getDescricao() { return _descricao; }
		public void setDescricao( String value ) { _descricao = value; }
	

}

