DROP TABLE FUNCIONARIO;
CREATE TABLE FUNCIONARIO (
        ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
        NOME VARCHAR(50),
        CPF VARCHAR(11),
        ENDERECO VARCHAR(50),
        IDADE INTEGER
    );
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FUNCIONARIO_PRIMARY_KEY PRIMARY KEY (ID);

insert into FUNCIONARIO (NOME, CPF, ENDERECO, IDADE) values ('Arnaldo da Silva', '11122233396', 'Al. Santos, 438', 40);
insert into FUNCIONARIO (NOME, CPF, ENDERECO, IDADE) values ('Maria Pereira', '22233311169', 'Rua da Consolacao, 123', 35);
insert into FUNCIONARIO (NOME, CPF, ENDERECO, IDADE) values ('Eduardo Andrade', '32060839823', 'Alameda Casa Branca', 29);
insert into FUNCIONARIO (NOME, CPF, ENDERECO, IDADE) values ('José Antônio', '44455566609', 'Rua um, 1', 25);

DROP TABLE DADOS_FUNCIONARIO;
CREATE TABLE DADOS_FUNCIONARIO (
        ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
        ID_FUNCIONARIO INTEGER CONSTRAINT ID_FUNCIONARIO_FK REFERENCES FUNCIONARIO NOT NULL,
        MAX_AUXILIO_ESTUDO REAL,
        PERCENT_REEMBOLSO_CURSO INTEGER,
        FAZ_REEMBOLSO_ESTUDO INTEGER NOT NULL DEFAULT 0
    );
ALTER TABLE DADOS_FUNCIONARIO ADD CONSTRAINT DADOS_FUNCIONARIO_PRIMARY_KEY PRIMARY KEY (ID, ID_FUNCIONARIO);

insert into DADOS_FUNCIONARIO (ID_FUNCIONARIO, MAX_AUXILIO_ESTUDO, PERCENT_REEMBOLSO_CURSO, FAZ_REEMBOLSO_ESTUDO) values (1, 60, 15, 1);
insert into DADOS_FUNCIONARIO (ID_FUNCIONARIO, MAX_AUXILIO_ESTUDO, PERCENT_REEMBOLSO_CURSO, FAZ_REEMBOLSO_ESTUDO) values (2, 45.5, 10, 1);
insert into DADOS_FUNCIONARIO (ID_FUNCIONARIO, MAX_AUXILIO_ESTUDO, PERCENT_REEMBOLSO_CURSO, FAZ_REEMBOLSO_ESTUDO) values (3, 45.5, 10, 1);
insert into DADOS_FUNCIONARIO (ID_FUNCIONARIO, MAX_AUXILIO_ESTUDO, PERCENT_REEMBOLSO_CURSO, FAZ_REEMBOLSO_ESTUDO) values (4, 45.5, 10, 1);

DROP TABLE CURSO_FUNCIONARIO;
CREATE TABLE CURSO_FUNCIONARIO (
        ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
        ID_FUNCIONARIO INTEGER CONSTRAINT ID_CURSO_FUNCIONARIO_FK REFERENCES FUNCIONARIO NOT NULL,
        ID_PARCELA INTEGER CONSTRAINT ID_PARCELA_FK REFERENCES PARCELA_CURSO NOT NULL,
        CURSO VARCHAR(50),
        INSTITUICAO VARCHAR(50),
        DATA_INICIO DATE,
        DURACAO_MESES INTEGER,
        JUSTIFICATIVA VARCHAR(50)
    );
ALTER TABLE CURSO_FUNCIONARIO ADD CONSTRAINT CURSO_FUNCIONARIO_PRIMARY_KEY PRIMARY KEY (ID, ID_FUNCIONARIO);

insert into CURSO_FUNCIONARIO (ID_FUNCIONARIO, ID_PARCELA, CURSO, INSTITUICAO, DATA_INICIO, DURACAO_MESES, JUSTIFICATIVA) values (1, 1, 'Curso Inglês', 'Escola Inglês', '2012-12-15', 12, 'Justificativa');
insert into CURSO_FUNCIONARIO (ID_FUNCIONARIO, ID_PARCELA, CURSO, INSTITUICAO, DATA_INICIO, DURACAO_MESES, JUSTIFICATIVA) values (2, 2, 'Curso Francês', 'Escola Francês', '2012-12-15', 12, 'Justificativa');
insert into CURSO_FUNCIONARIO (ID_FUNCIONARIO, ID_PARCELA, CURSO, INSTITUICAO, DATA_INICIO, DURACAO_MESES, JUSTIFICATIVA) values (3, 3, 'Curso Espanhol', 'Escola Espanhol', '2011-06-15', 24, 'Justificativa');
insert into CURSO_FUNCIONARIO (ID_FUNCIONARIO, ID_PARCELA, CURSO, INSTITUICAO, DATA_INICIO, DURACAO_MESES, JUSTIFICATIVA) values (4, 4, 'Curso Alemão', 'Escola Alemão', '2010-03-15', 24, 'Justificativa');
insert into CURSO_FUNCIONARIO (ID_FUNCIONARIO, ID_PARCELA, CURSO, INSTITUICAO, DATA_INICIO, DURACAO_MESES, JUSTIFICATIVA) values (5, 5, 'Curso Alemão', 'Escola Alemão', '2010-03-15', 24, 'Justificativa');

DROP TABLE PARCELA_CURSO;
CREATE TABLE PARCELA_CURSO (
        ID_PARCELA INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
        DATA_VENCIMENTO DATE,
        VALOR REAL,
        VALOR_REEMBOLSO REAL,
        ABATER_AUX_ESTUDO INTEGER NOT NULL DEFAULT 0,
        DATA_APR_CHEFE DATE
    );
ALTER TABLE PARCELA_CURSO ADD CONSTRAINT PARCELA_CURSO_PRIMARY_KEY PRIMARY KEY (ID_PARCELA);

insert into PARCELA_CURSO (DATA_VENCIMENTO, VALOR, VALOR_REEMBOLSO, ABATER_AUX_ESTUDO, DATA_APR_CHEFE) values ('2012-12-15', 100, 50, 1, '2012-12-15');
insert into PARCELA_CURSO (DATA_VENCIMENTO, VALOR, VALOR_REEMBOLSO, ABATER_AUX_ESTUDO, DATA_APR_CHEFE) values ('2012-12-15', 100, 50, 1, '2012-12-15');
insert into PARCELA_CURSO (DATA_VENCIMENTO, VALOR, VALOR_REEMBOLSO, ABATER_AUX_ESTUDO, DATA_APR_CHEFE) values ('2012-12-15', 100, 50, 1, '2012-12-15');
insert into PARCELA_CURSO (DATA_VENCIMENTO, VALOR, VALOR_REEMBOLSO, ABATER_AUX_ESTUDO, DATA_APR_CHEFE) values ('2012-12-15', 100, 50, 1, '2012-12-15');
insert into PARCELA_CURSO (DATA_VENCIMENTO, VALOR, VALOR_REEMBOLSO, ABATER_AUX_ESTUDO, DATA_APR_CHEFE) values ('2012-12-15', 100, 50, 1, '2012-12-15');

DROP TABLE TIPO_DESPESA;
CREATE TABLE TIPO_DESPESA (
        ID_DESPESA INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
        DESCRICAO VARCHAR(50)
    );
ALTER TABLE TIPO_DESPESA ADD CONSTRAINT TIPO_DESPESA_PRIMARY_KEY PRIMARY KEY (ID_DESPESA);

DROP TABLE REEMBOLSO;
CREATE TABLE REEMBOLSO (
        ID_REEMBOLSO INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
        ID_PARCELA INTEGER CONSTRAINT ID_REEMBOLSO_PARCELA_FK REFERENCES PARCELA_CURSO NOT NULL,
        DATA_PEDIDO DATE,
        DATA_APROVACAO_CHEFE DATE,
        DATA_APROVACAO_DIRETOR DATE,
        DATA_APROVACAO_FINANC DATE,
        DATA_PAGAMENTO DATE,
        FINALIDADE VARCHAR(50),
        VALOR_REEMBOLSO REAL,
        DATA_CONTABILIZACAO DATE,
        TIPO_REEMBOLSO VARCHAR(50)
    );
ALTER TABLE REEMBOLSO ADD CONSTRAINT REEMBOLSO_PRIMARY_KEY PRIMARY KEY (ID_REEMBOLSO);

insert into REEMBOLSO (ID_PARCELA, DATA_PEDIDO, DATA_APROVACAO_CHEFE, DATA_APROVACAO_DIRETOR, DATA_APROVACAO_FINANC, DATA_PAGAMENTO, FINALIDADE, VALOR_REEMBOLSO, DATA_CONTABILIZACAO, TIPO_REEMBOLSO) values (1, '2012-12-15', '2012-12-15', '2012-12-15', '2012-12-15', '2012-12-15', 'Finalidade', 50.55, '2012-12-15', 'tipo reembolso');

DROP TABLE AUDIT_LOG;
CREATE TABLE AUDIT_LOG (
        ID_LOG INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
        LEVEL VARCHAR(10),
        MSG VARCHAR(100)
    );
ALTER TABLE AUDIT_LOG ADD CONSTRAINT AUDIT_LOG_PRIMARY_KEY PRIMARY KEY (ID_LOG);

select * from audit_log
select * from reembolso



