// =======================================================================================
// Warning. Do not edit this file directly.  This file was built with the SPL generator.
// Eduardo Andrade - 2014-04-09 13:12:38 -0300
// =======================================================================================
package br.com.splgenerator.web.cadastro;

import java.io.Serializable;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.component.html.HtmlDataTable;
import javax.faces.context.FacesContext;

@ManagedBean
@SessionScoped
public class GerenciarTipoDespesa implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@ManagedProperty(value="#{jdbcDao}")
	private br.com.splgenerator.dao.ModRhDao dao;
	
	@ManagedProperty(value="#{logTXT}")
	private br.com.splgenerator.audit.ILog log;
	
	private HtmlDataTable htmlDataTable;
	
	
	private br.com.splgenerator.model.cadastro.TipoDespesa _novoTipoDespesa;
	
	private br.com.splgenerator.model.cadastro.TipoDespesa _editarTipoDespesa;
	
	
	public GerenciarTipoDespesa() { 
	
		_novoTipoDespesa = new  br.com.splgenerator.model.cadastro.TipoDespesa();
		_editarTipoDespesa = null;
	}
	
	public void setDao(br.com.splgenerator.dao.ModRhDao dao) {
		this.dao = dao;
	}
	
	public void setLog(br.com.splgenerator.audit.ILog log) {
		this.log = log;
	}
	
	public HtmlDataTable getHtmlDataTable() {
        return htmlDataTable;
    }

    public void setHtmlDataTable(HtmlDataTable htmlDataTable) {
        this.htmlDataTable = htmlDataTable;
    }
	
	
	public java.util.List<br.com.splgenerator.model.cadastro.TipoDespesa> getTipoDespesas() {
		log.log("TRACE", "Executando getTipoDespesas()...");
	
									return dao.getTipoDespesas();
								
	}
	
	public String atualizarTipoDespesa() {
		log.log("TRACE", "Executando atualizarTipoDespesa()...");
	
									dao.atualizarTipoDespesa(_editarTipoDespesa);
									addFacesMessage("Tipo Despesa editado com sucesso!");
									return "gerenciarTipoDespesa";
								
	}
	
	public String salvarTipoDespesa() {
		log.log("TRACE", "Executando salvarTipoDespesa()...");
	
									dao.salvarTipoDespesa(_novoTipoDespesa);
									addFacesMessage("Tipo Despesa adicionado com sucesso!");
									this._novoTipoDespesa = new br.com.splgenerator.model.cadastro.TipoDespesa();
									return "gerenciarTipoDespesa";
								
	}
	
	public String removerTipoDespesa() {
		log.log("TRACE", "Executando removerTipoDespesa()...");
	
									dao.removerTipoDespesa((br.com.splgenerator.model.cadastro.TipoDespesa) htmlDataTable.getRowData());
									addFacesMessage("Tipo Despesa removido com sucesso!");
									return null;
								
	}
	
	public String selecionarTipoDespesa() {
		log.log("TRACE", "Executando selecionarTipoDespesa()...");
	
									this._editarTipoDespesa = (br.com.splgenerator.model.cadastro.TipoDespesa) htmlDataTable.getRowData();
									return "editarTipoDespesa";
								
	}
	
	
	
	public br.com.splgenerator.model.cadastro.TipoDespesa getNovotipodespesa() { return _novoTipoDespesa; }
	public void setNovotipodespesa( br.com.splgenerator.model.cadastro.TipoDespesa value ) { _novoTipoDespesa = value; }
	
	public br.com.splgenerator.model.cadastro.TipoDespesa getEditartipodespesa() { return _editarTipoDespesa; }
	public void setEditartipodespesa( br.com.splgenerator.model.cadastro.TipoDespesa value ) { _editarTipoDespesa = value; }
	
	
	private void addFacesMessage(String message) {
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(message));
	}

}
